services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "https://sourceforge.net/projects/android-x86/files/Release%209.0/android-x86_64-9.0-r2.iso/download"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "32G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
